version: 2
defaults: &defaults
  docker:
    - image: ubuntu:18.04
jobs:
  build_linux:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Id
          command: cat /etc/*release
      - run:
          name: Setup requirements
          command: apt-get install git ant
      - run:
          name: Build for Linux
          command: bash scripts/build_linux.sh
      - store_artifacts:
          path: linux/_CPack_Packages
      - run:
          name: Update Navit-Download-Center
          command: |
            bash scripts/update_download_center.sh
  build_win32:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Prepare the Windows build environment
          command: |
            apt-get update 
            apt-get install -y mingw-w64 mingw-w64-tools default-jdk nsis libsaxonb-java curl
      - run:
          name: Build for Windows
          command: |
            bash scripts/build_win32.sh
      - store_artifacts:
          path: win32/navit.exe
      - run:
          name: Update Navit-Download-Center
          command: |
            bash scripts/update_download_center.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux:
      - build_win32:
